export interface ChapterMeta {
  title: string;
  startStep: number;
  endStep: number;
}

export interface PCStepState {
  activeThread: "producer" | "consumer" | "none";
  producerState: "running" | "suspended" | "idle" | "terminated";
  consumerState: "running" | "suspended" | "idle" | "terminated";
  producerCodeLine: number | null;
  consumerCodeLine: number | null;
  registerRp: number | null;
  registerRc: number | null;
  sharedMemoryCount: number;
  isContextSwitch: boolean;
  explanation: string;
  noteTitle?: string;
  noteContent?: string;
  toastMessage?: string;
  chapter: string;
  buffer: ("item" | null)[];
}

export interface PCScenario {
  id: string;
  title: string;
  description: string;
  chapters: ChapterMeta[];
  steps: PCStepState[];
}

const INITIAL_BUFFER = ["item", "item", "item", null, null, null, null, null] as ("item" | null)[];

export const PRODUCER_CONSUMER_SCENARIO_A: PCScenario = {
  id: "producer-consumer-race-condition",
  title: "The Lost Update Problem",
  description: "Visualize how lack of synchronization leads to data corruption during context switches.",
  chapters: [
    { title: "What Are We Watching?", startStep: 0, endStep: 3 },
    { title: "The Race Begins (Scenario A)", startStep: 4, endStep: 11 },
    { title: "The Verdict", startStep: 12, endStep: 13 },
  ],
  steps: [
    {
      chapter: "What Are We Watching?",
      activeThread: "none",
      producerState: "idle",
      consumerState: "idle",
      producerCodeLine: null,
      consumerCodeLine: null,
      registerRp: null,
      registerRc: null,
      sharedMemoryCount: 3,
      isContextSwitch: false,
      buffer: [...INITIAL_BUFFER],
      explanation: "Welcome to Episode 5. We have a shared buffer with 3 items. A Producer thread wants to add an item, and a Consumer thread wants to remove one.",
      noteTitle: "The Setup",
      noteContent: "The memory variable 'count' keeps track of how many items are in the buffer. Right now, count = 3.",
    },
    {
      chapter: "What Are We Watching?",
      activeThread: "producer",
      producerState: "idle",
      consumerState: "idle",
      producerCodeLine: null,
      consumerCodeLine: null,
      registerRp: null,
      registerRc: null,
      sharedMemoryCount: 3,
      isContextSwitch: false,
      buffer: [...INITIAL_BUFFER],
      explanation: "To add an item, the Producer does: count = count + 1. But in assembly, this is NOT one instruction. It's three separate instructions: LOAD, INC, and STORE.",
      noteTitle: "Not Atomic",
      noteContent: "An atomic operation is something that happens completely or not at all, with no interruptions. 'count++' is NOT atomic. The CPU breaks it down into three separate read-modify-write steps.",
    },
    {
      chapter: "What Are We Watching?",
      activeThread: "consumer",
      producerState: "idle",
      consumerState: "idle",
      producerCodeLine: null,
      consumerCodeLine: null,
      registerRp: null,
      registerRc: null,
      sharedMemoryCount: 3,
      isContextSwitch: false,
      buffer: [...INITIAL_BUFFER],
      explanation: "Similarly, the Consumer does: count = count - 1. This also breaks down into LOAD, DEC, and STORE instructions.",
      noteTitle: "Read-Modify-Write",
      noteContent: "Both threads will perform a Read-Modify-Write sequence on the exact same shared variable (count). This is dangerous if they aren't synchronized.",
    },
    {
      chapter: "What Are We Watching?",
      activeThread: "none",
      producerState: "idle",
      consumerState: "idle",
      producerCodeLine: null,
      consumerCodeLine: null,
      registerRp: null,
      registerRc: null,
      sharedMemoryCount: 3,
      isContextSwitch: false,
      buffer: [...INITIAL_BUFFER],
      explanation: "Let's watch what happens when both threads run at the same time and the OS performs a Context Switch at the worst possible moment.",
      noteTitle: "Registers",
      noteContent: "Notice that each thread has its own private CPU register (Rp for Producer, Rc for Consumer). They don't share registers, only the main Memory.",
      toastMessage: "Starting Simulation",
    },
    // Chapter 2: The Race Begins
    {
      chapter: "The Race Begins (Scenario A)",
      activeThread: "producer",
      producerState: "running",
      consumerState: "idle",
      producerCodeLine: 0,
      consumerCodeLine: null,
      registerRp: 3,
      registerRc: null,
      sharedMemoryCount: 3,
      isContextSwitch: false,
      buffer: [...INITIAL_BUFFER],
      explanation: "Producer Step 1: LOAD Rp, count. The Producer reads the current count (3) from shared memory into its private register (Rp).",
    },
    {
      chapter: "The Race Begins (Scenario A)",
      activeThread: "producer",
      producerState: "running",
      consumerState: "idle",
      producerCodeLine: 1,
      consumerCodeLine: null,
      registerRp: 4,
      registerRc: null,
      sharedMemoryCount: 3,
      isContextSwitch: false,
      buffer: ["item", "item", "item", "item", null, null, null, null],
      explanation: "Producer Step 2: INC Rp. The Producer increments its register to 4. (The item is logically added to the buffer). Notice something important: Memory still says count = 3!",
      noteTitle: "Memory Hasn't Changed",
      noteContent: "The Producer has updated its private scratchpad (register), but hasn't saved the result back to shared memory yet.",
    },
    {
      chapter: "The Race Begins (Scenario A)",
      activeThread: "none",
      producerState: "suspended",
      consumerState: "idle",
      producerCodeLine: 1,
      consumerCodeLine: null,
      registerRp: 4,
      registerRc: null,
      sharedMemoryCount: 3,
      isContextSwitch: true,
      buffer: ["item", "item", "item", "item", null, null, null, null],
      explanation: "Wait! A hardware interrupt occurs. The CPU scheduler decides to switch to the Consumer thread. The Producer is suspended mid-update.",
      toastMessage: "Context Switch!",
    },
    {
      chapter: "The Race Begins (Scenario A)",
      activeThread: "consumer",
      producerState: "suspended",
      consumerState: "running",
      producerCodeLine: 1,
      consumerCodeLine: 0,
      registerRp: 4,
      registerRc: 3,
      sharedMemoryCount: 3,
      isContextSwitch: false,
      buffer: ["item", "item", "item", "item", null, null, null, null],
      explanation: "Consumer Step 1: LOAD Rc, count. The Consumer reads the count from memory. Since the Producer never STORED its result, the Consumer reads a stale value: 3.",
      noteTitle: "Stale Data",
      noteContent: "The Consumer thinks there are 3 items, completely unaware that the Producer is in the middle of adding a 4th item.",
    },
    {
      chapter: "The Race Begins (Scenario A)",
      activeThread: "consumer",
      producerState: "suspended",
      consumerState: "running",
      producerCodeLine: 1,
      consumerCodeLine: 1,
      registerRp: 4,
      registerRc: 2,
      sharedMemoryCount: 3,
      isContextSwitch: false,
      buffer: ["item", "item", "item", null, null, null, null, null], // removed the newly added item visually to show consumer action
      explanation: "Consumer Step 2: DEC Rc. The Consumer decrements its private register to 2. (An item is logically removed).",
    },
    {
      chapter: "The Race Begins (Scenario A)",
      activeThread: "consumer",
      producerState: "suspended",
      consumerState: "running",
      producerCodeLine: 1,
      consumerCodeLine: 2,
      registerRp: 4,
      registerRc: 2,
      sharedMemoryCount: 2,
      isContextSwitch: false,
      buffer: ["item", "item", "item", null, null, null, null, null],
      explanation: "Consumer Step 3: STORE Rc, count. The Consumer saves its result back. Shared memory is now officially count = 2. The Consumer finishes.",
    },
    {
      chapter: "The Race Begins (Scenario A)",
      activeThread: "none",
      producerState: "suspended",
      consumerState: "terminated",
      producerCodeLine: 1,
      consumerCodeLine: 2,
      registerRp: 4,
      registerRc: 2,
      sharedMemoryCount: 2,
      isContextSwitch: true,
      buffer: ["item", "item", "item", null, null, null, null, null],
      explanation: "The Consumer is done. The CPU scheduler switches context back to the Producer to finish its work.",
      toastMessage: "Context Switch!",
    },
    {
      chapter: "The Race Begins (Scenario A)",
      activeThread: "producer",
      producerState: "running",
      consumerState: "terminated",
      producerCodeLine: 2,
      consumerCodeLine: 2,
      registerRp: 4,
      registerRc: 2,
      sharedMemoryCount: 4,
      isContextSwitch: false,
      buffer: ["item", "item", "item", "item", null, null, null, null], // Visual buffer reflects 4 conceptually
      explanation: "Producer Step 3: STORE Rp, count. The Producer resumes exactly where it left off, and writes Rp = 4 into shared memory. OVERWRITING the Consumer's work!",
      noteTitle: "Lost Update",
      noteContent: "The Consumer's 'count = 2' update was completely wiped out. This is the definition of a Race Condition.",
    },
    // Chapter 3: The Verdict
    {
      chapter: "The Verdict",
      activeThread: "none",
      producerState: "terminated",
      consumerState: "terminated",
      producerCodeLine: 2,
      consumerCodeLine: 2,
      registerRp: 4,
      registerRc: 2,
      sharedMemoryCount: 4,
      isContextSwitch: false,
      buffer: ["item", "item", "item", "item", null, null, null, null],
      explanation: "Final result: count = 4. But we started with 3, added one, and removed one. The EXPECTED result was 3! The system is now corrupted.",
      noteTitle: "The Solution",
      noteContent: "To fix this, we need 'Mutual Exclusion'. Only one thread should be allowed to manipulate the shared variable at a time. (Coming in Episode 6: Mutex Locks!).",
    },
    {
      chapter: "The Verdict",
      activeThread: "none",
      producerState: "terminated",
      consumerState: "terminated",
      producerCodeLine: 2,
      consumerCodeLine: 2,
      registerRp: 4,
      registerRc: 2,
      sharedMemoryCount: 4,
      isContextSwitch: false,
      buffer: ["item", "item", "item", "item", null, null, null, null],
      explanation: "Think of it like a shared notebook: Both people read it, did some math on scratch paper, and wrote back their answers. The last person to write wins.",
    }
  ]
};

export const PRODUCER_CONSUMER_SCENARIO_B: PCScenario = {
  id: "producer-consumer-race-condition-b",
  title: "The Lost Update Problem (Reverse Interleaving)",
  description: "Visualize how a different context switch timing causes the opposite corruption.",
  chapters: [
    { title: "Scenario B: Producer Writes First", startStep: 0, endStep: 7 },
  ],
  steps: [
    {
      chapter: "Scenario B: Producer Writes First",
      activeThread: "producer",
      producerState: "running",
      consumerState: "idle",
      producerCodeLine: 0,
      consumerCodeLine: null,
      registerRp: 3,
      registerRc: null,
      sharedMemoryCount: 3,
      isContextSwitch: false,
      buffer: [...INITIAL_BUFFER],
      explanation: "Producer reads count = 3 into Rp.",
    },
    {
      chapter: "Scenario B: Producer Writes First",
      activeThread: "none",
      producerState: "suspended",
      consumerState: "idle",
      producerCodeLine: 0,
      consumerCodeLine: null,
      registerRp: 3,
      registerRc: null,
      sharedMemoryCount: 3,
      isContextSwitch: true,
      buffer: [...INITIAL_BUFFER],
      explanation: "Immediate context switch before the Producer even increments!",
    },
    {
      chapter: "Scenario B: Producer Writes First",
      activeThread: "consumer",
      producerState: "suspended",
      consumerState: "running",
      producerCodeLine: 0,
      consumerCodeLine: 1,
      registerRp: 3,
      registerRc: 2,
      sharedMemoryCount: 3,
      isContextSwitch: false,
      buffer: ["item", "item", null, null, null, null, null, null],
      explanation: "Consumer LOADs 3, and DECs to 2.",
    },
    {
      chapter: "Scenario B: Producer Writes First",
      activeThread: "none",
      producerState: "suspended",
      consumerState: "suspended",
      producerCodeLine: 0,
      consumerCodeLine: 1,
      registerRp: 3,
      registerRc: 2,
      sharedMemoryCount: 3,
      isContextSwitch: true,
      buffer: ["item", "item", null, null, null, null, null, null],
      explanation: "Context switch back to Producer!",
    },
    {
      chapter: "Scenario B: Producer Writes First",
      activeThread: "producer",
      producerState: "running",
      consumerState: "suspended",
      producerCodeLine: 2,
      consumerCodeLine: 1,
      registerRp: 4,
      registerRc: 2,
      sharedMemoryCount: 4,
      isContextSwitch: false,
      buffer: ["item", "item", "item", "item", null, null, null, null],
      explanation: "Producer INCs to 4, and STOREs 4 to Memory.",
    },
    {
      chapter: "Scenario B: Producer Writes First",
      activeThread: "none",
      producerState: "suspended",
      consumerState: "suspended",
      producerCodeLine: 2,
      consumerCodeLine: 1,
      registerRp: 4,
      registerRc: 2,
      sharedMemoryCount: 4,
      isContextSwitch: true,
      buffer: ["item", "item", "item", "item", null, null, null, null],
      explanation: "Context switch back to Consumer!",
    },
    {
      chapter: "Scenario B: Producer Writes First",
      activeThread: "consumer",
      producerState: "terminated",
      consumerState: "running",
      producerCodeLine: 2,
      consumerCodeLine: 2,
      registerRp: 4,
      registerRc: 2,
      sharedMemoryCount: 2,
      isContextSwitch: false,
      buffer: ["item", "item", null, null, null, null, null, null],
      explanation: "Consumer STOREs its Rc = 2 into memory. Overwriting the 4!",
    },
    {
      chapter: "Scenario B: Producer Writes First",
      activeThread: "none",
      producerState: "terminated",
      consumerState: "terminated",
      producerCodeLine: 2,
      consumerCodeLine: 2,
      registerRp: 4,
      registerRc: 2,
      sharedMemoryCount: 2,
      isContextSwitch: false,
      buffer: ["item", "item", null, null, null, null, null, null],
      explanation: "Final result: count = 2. Still wrong (expected 3), but this time we lost the Producer's update.",
    },
  ]
};
